# Site wide configuration

title: X-Spirit
description: "Wei Zhang's Personal Blog"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url:  #//mmistakes.github.io/skinny-bones-jekyll

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Wei Zhang
  web: http://zhangwei217245.github.io
  email: zhangwei217245@gmail.com
  twitter: zhangwei217245
  bio: "Yet another programmer."
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: +zhangwei217245
    ad-client:
    ad-slot:
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
